### ISSUE TITLE
fullCapacity is limited to 22Ah

### ISSUE THREAD

**Issue by avandalen** [PonyPC/LTC2944-Arduino-Library#1]
Hi,
My battery is 90Ah, but I can’t set fullCapacity higher than 22Ah.
The LTC2944 can handle maximum 330Ah , (with a maximum current of 15A), see the datasheet:

“ Choosing RSENSE = 50mV/IMAX is not sufficient in applications where the battery capacity (QBAT) is very large compared to the maximum current (IMAX)”

QBAT > IMAX * 22Hours
QBAT > 15A * 22 = 330Ah
QBAT (90Ah) < 330Ah so this is no problem

**Comment by PonyPC** [comment]
Sorry for long time, u can modify code to be compatible with your sensor.

**Comment by PonyPC** [comment]
replace uint16_t _batteryCapacity with uint32_t _batteryCapacity
