### ISSUE TITLE
setRawAccumulatedCharge() has no effect?

### ISSUE THREAD

**Issue by avandalen** [PonyPC/LTC2944-Arduino-Library#2]
Hi

I want to use setRawAccumulatedCharge() instead of setBatteryCapacity() but is seems that it has no effect. 
When I set setRawAccumulatedCharge(32000) , Raw Accumulated Charge is still 65535.

**Comment by PonyPC** [comment]
replace void setRawAccumulatedCharge(uint16_t charge); to void setRawAccumulatedCharge(uint32_t charge); if you have integer range problem.

**Comment by PonyPC** [comment]
consulting ur sellsman
